"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1500

add_newline = true

right_format = """
$cmd_duration\
"""

format = """
[ î‚¶](fg:color_identity)\
$os\
$username\
$hostname\
[î‚´ ](fg:color_identity)\

$directory\

$c\
$dotnet\
$java\
$kotlin\
$dart\
$nodejs\
$golang\
$rust\
$python\
$ruby\
$php\
$lua\
$perl\
$swift\
$haskell\
$elixir\
$julia\
$crystal\
$zig\
$kubernetes\
$terraform\

$git_branch\
$git_status\

$line_break\
$line_break\
$character\
"""

palette = "default"

[palettes.default]

color_cmd_duration = "#a1a1a1"

color_identity = "#51a2da"

color_directory = "#e0b757"

color_git = "#ee4b27"

color_c = "#6170c2"
color_java = "#3871aa"
color_kotlin = "#993ef9"
color_dart = "#2ab4f2"
color_nodejs = "#60b248"
color_golang = "#007d9c"
color_rust = "#f64a00"
color_python = "#3670a0"
color_ruby = "#a91401"
color_php = "#8993be"
color_lua = "#000080"
color_perl = "#0298c3"
color_swift = "#f05138"
color_haskell = "#5e5086"
color_elixir = "#4e2a8e"
color_julia = "#a270ba"
color_crystal = "#f8f8f8"
color_zig = "#f7a41d"
color_kubernetes = "#326ce5"
color_terraform = "#623ce4"

text_dart = "#04599c"
text_red = "#eb4d28"
text_white = "#f2f2f2"
text_black = "#1e1e1e"

[character]
error_symbol = "[ â¯](bold text_red)"
success_symbol = "[ â¯](bold text_white)"

[cmd_duration]
format = "[î‚¶](fg:color_cmd_duration)[ï‰’ $duration](bg:color_cmd_duration fg:text_black)[î‚´ ](fg:color_cmd_duration)"
min_time = 500

[directory]
style = "bg:color_directory fg:text_black"
format = "[î‚¶](fg:color_directory)[$path]($style)[î‚´ ](fg:color_directory)"
truncation_length = 0
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ Documents"
"Downloads" = "ï€™  Downloads"
"Music" = "ï€  Music"
"Pictures" = "ï€¾  Pictures"

[line_break]
disabled = false

[fill]
symbol = " "

[os]
format = "[$symbol]($style)"
style = "bg:color_identity fg:text_white"
disabled = false

[username]
disabled = false
format = "[ $user]($style)"
show_always = true
style_root = "bg:color_identity fg:text_red"
style_user = "bg:color_identity fg:text_black"

[hostname]
format = "[ @$hostname]($style)"
ssh_only = true
ssh_symbol = "î¬ "
style = "bg:color_identity fg:text_black"

[git_branch]
symbol = "ï˜"
style = "bg:color_git fg:text_black"
format = "[î‚¶](fg:color_git)[$symbol $branch]($style)[î‚´ ](fg:color_git)"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "ï’"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
format = '[î‚¶](fg:color_git)[($all_status$ahead_behind)]($style)[î‚´ ](fg:color_git)'
style = "bold bg:color_git fg:text_black"

# Code symbols
[c]
format = '[î‚¶](fg:color_c)[$symbol]($style)[î‚´ ](fg:color_c)'
style = "bg:color_c fg:text_white"
symbol = " î˜ "

[dotnet]
format = '[î‚¶](fg:color_dotnet)[$symbol]($style)[î‚´ ](fg:color_dotnet)'
style = "bg:color_dotnet fg:text_white"
symbol = " î¿ "

[java]
format = '[î‚¶](fg:color_java)[$symbol]($style)[î‚´ ](fg:color_java)'
style = "bg:color_java fg:text_white"
symbol = " î‰– "

[kotlin]
format = '[î‚¶](fg:color_kotlin)[$symbol]($style)[î‚´ ](fg:color_kotlin)'
style = "bg:color_kotlin fg:text_white"
symbol = " î˜´ "

[dart]
format = '[î‚¶](fg:color_dart)[$symbol]($style)[î‚´ ](fg:color_dart)'
style = "bg:color_dart fg:text_dart"
symbol = " î™Œ "

[nodejs]
format = '[î‚¶](fg:color_nodejs)[$symbol($version)]($style)[î‚´ ](fg:color_nodejs)'
style = "bg:color_nodejs fg:text_white"
symbol = "îœ˜ "

[golang]
format = '[î‚¶](fg:color_golang)[$symbol($version)]($style)[î‚´ ](fg:color_golang)'
style = "bg:color_golang fg:text_white"
symbol = "î™ "

[rust]
format = '[î‚¶](fg:color_rust)[$symbol($version)]($style)[î‚´ ](fg:color_rust)'
style = "bg:color_rust fg:text_black"
symbol = " î¨ "

[python]
format = '[î‚¶](fg:color_python)[$symbol($version)]($style)[î‚´ ](fg:color_python)'
style = "bg:color_python fg:text_white"
symbol = " îœ¼ "

[ruby]
format = '[î‚¶](fg:color_ruby)[$symbol($version)]($style)[î‚´ ](fg:color_ruby)'
style = "bg:color_ruby fg:text_white"
symbol = " îœ¹ "

[php]
format = '[î‚¶](fg:color_php)[$symbol($version)]($style)[î‚´ ](fg:color_php)'
style = "bg:color_php fg:text_white"
symbol = " îœ½ "

[lua]
format = '[î‚¶](fg:color_lua)[$symbol($version)]($style)[î‚´ ](fg:color_lua)'
style = "bg:color_lua fg:text_white"
symbol = " î˜  "

[perl]
format = '[î‚¶](fg:color_perl)[$symbol($version)]($style)[î‚´ ](fg:color_perl)'
style = "bg:color_perl fg:text_white"
symbol = " î© "

[swift]
format = '[î‚¶](fg:color_swift)[$symbol($version)]($style)[î‚´ ](fg:color_swift)'
style = "bg:color_swift fg:text_white"
symbol = " î• "

[haskell]
format = '[î‚¶](fg:color_haskell)[$symbol($version)]($style)[î‚´ ](fg:color_haskell)'
style = "bg:color_haskell fg:text_white"
symbol = " î· "

[elixir]
format = '[î‚¶](fg:color_elixir)[$symbol($version)]($style)[î‚´ ](fg:color_elixir)'
style = "bg:color_elixir fg:text_white"
symbol = " î˜­ "

[julia]
format = '[î‚¶](fg:color_julia)[$symbol($version)]($style)[î‚´ ](fg:color_julia)'
style = "bg:color_julia fg:text_white"
symbol = " î˜¤ "

[crystal]
format = '[î‚¶](fg:color_crystal)[$symbol($version)]($style)[î‚´ ](fg:color_crystal)'
style = "bg:color_crystal fg:text_black"
symbol = " î˜¯ "

[zig]
format = '[î‚¶](fg:color_zig)[$symbol($version)]($style)[î‚´ ](fg:color_zig)'
style = "bg:color_zig fg:text_white"
symbol = " îš© "

[kubernetes]
format = '[î‚¶](fg:color_kubernetes)[$symbol($version)]($style)[î‚´ ](fg:color_kubernetes)'
style = "bg:color_kubernetes fg:text_white"
symbol = " ó±ƒ¾ "

[terraform]
format = '[î‚¶](fg:color_terraform)[$symbol($version)]($style)[î‚´ ](fg:color_terraform)'
style = "bg:color_terraform fg:text_white"
symbol = " ó±¢ "

# OS Symbols
[os.symbols]
AIX = "â¿ "
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ïŒ¢ "
Fedora = "ïŒ‹ "
FreeBSD = "ïŒŒ "
Garuda = "ïŒ· "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "î¯† "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ó°£­ "
NetBSD = "ï€¤ "
NixOS = "ó±„… "
OpenBSD = "ïŒ¨ "
OpenCloudOS = "â˜ï¸ "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "î½ "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Ultramarine = "ğŸ”· "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

